/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* "" */
/* #undef CLEAR_PASS */

/* Define to 1 if the `closedir' function returns void instead of `int'. */
/* #undef CLOSEDIR_VOID */

/* "" */
#define DOMAINS_DIR "domains"

/* "" */
#define ENABLE_AUTH_LOGGING 1

/* "" */
/* #undef ENABLE_LEARN_PASSWORDS */

/* "" */
#define ENABLE_LOGGING 3

/* "" */
#define ENABLE_MYSQL_LIMITS 1

/* "" */
/* #undef ENABLE_PASSWD */

/* "" */
#define ENABLE_SQL_LOGGING 1

/* "" */
#define FILE_LOCKING 1

/* "" */
/* #undef FILE_SYNC */

/* "" */
#define HAS_SHADOW 1

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the `bzero' function. */
#define HAVE_BZERO 1

/* Define to 1 if you have the <crypt.h> header file. */
#define HAVE_CRYPT_H 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the `dup2' function. */
#define HAVE_DUP2 1

/* Define to 1 if you have the <err.h> header file. */
#define HAVE_ERR_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `fdatasync' function. */
#define HAVE_FDATASYNC 1

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `gethostname' function. */
#define HAVE_GETHOSTNAME 1

/* Define to 1 if you have the `getpass' function. */
#define HAVE_GETPASS 1

/* Define to 1 if you have the `getspnam' function. */
#define HAVE_GETSPNAM 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `crypt' library (-lcrypt). */
#define HAVE_LIBCRYPT 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the `mkdir' function. */
#define HAVE_MKDIR 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the `rmdir' function. */
#define HAVE_RMDIR 1

/* Define to 1 if you have the <shadow.h> header file. */
#define HAVE_SHADOW_H 1

/* Define to 1 if you have the `socket' function. */
#define HAVE_SOCKET 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the `strspn' function. */
#define HAVE_STRSPN 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the <syslog.h> header file. */
#define HAVE_SYSLOG_H 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/file.h> header file. */
#define HAVE_SYS_FILE_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `utime' function. */
#define HAVE_UTIME 1

/* Define to 1 if you have the <utime.h> header file. */
#define HAVE_UTIME_H 1

/* Define to 1 if `utime(file, NULL)' sets file's timestamp to the present. */
#define HAVE_UTIME_NULL 1

/* Define to 1 if you have the `warn' function. */
#define HAVE_WARN 1

/* "" */
/* #undef IP_ALIAS_DOMAINS */

/* "" */
#define LOG_NAME "vpopmail"

/* "" */
/* #undef MAILDROP */

/* "" */
/* #undef MAILDROP_PROG */

/* "" */
#define MAKE_SEEKABLE 1

/* "" */
#define MANY_DOMAINS 1

/* "" */
#define MD5_PASSWORDS 1

/* "" */
/* #undef MYSQL_REPLICATION */

/* "" */
#define ONCHANGE_SCRIPT 1

/* "" */
/* #undef OPEN_SMTP_CUR_FILE */

/* "" */
/* #undef OPEN_SMTP_LOK_FILE */

/* "" */
/* #undef OPEN_SMTP_TMP_FILE */

/* Name of package */
#define PACKAGE "vpopmail"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "vpopmail"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "vpopmail 5.4.27"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "vpopmail"

/* Define to the version of this package. */
#define PACKAGE_VERSION "5.4.27"

/* "" */
/* #undef POP_AUTH_OPEN_RELAY */

/* "" */
#define PS_COMMAND "ps axww"

/* "" */
#define QMAILDIR "/var/qmail"

/* "" */
#define QMAILINJECT "/var/qmail/bin/qmail-inject"

/* "" */
#define QMAILNEWMRH "/var/qmail/bin/qmail-newmrh"

/* "" */
#define QMAILNEWU "/var/qmail/bin/qmail-newu"

/* "" */
/* #undef QMAIL_EXT */

/* "" */
/* #undef REBUILD_TCPSERVER */

/* "" */
/* #undef RELAY_CLEAR_MINUTES */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* "" */
#define SPAMASSASSIN 1

/* "" */
#define SPAMC_PROG "/usr/bin/spamc"

/* "" */
/* #undef SQWEBMAIL_PASS */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* "" */
/* #undef TCPRULES_PROG */

/* "" */
/* #undef TCP_FILE */

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* "" */
#define USERS_BIG_DIR 1

/* "" */
/* #undef USE_CDB */

/* "" */
/* #undef USE_LDAP */

/* "" */
#define USE_MYSQL 1

/* "" */
/* #undef USE_ORACLE */

/* "" */
/* #undef USE_POSTGRES */

/* "" */
#define USE_SQL 1

/* "" */
/* #undef USE_SYBASE */

/* "" */
#define VALIAS 1

/* Version number of package */
#define VERSION "5.4.27"

/* "" */
#define VLIMITS_DEFAULT_FILE "/home/vpopmail/etc/vlimits.default"

/* "" */
#define VPOPGROUP "vchkpw"

/* "" */
#define VPOPMAILDIR "/home/vpopmail"

/* "" */
#define VPOPMAILGID 1004

/* "" */
#define VPOPMAILUID 1008

/* "" */
#define VPOPUSER "vpopmail"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
