#!/bin/sh -e
package/compile
cd package && sed -i.bak 's|/command|/usr/sbin|' boot.inittab
cd ../command && sed -i.bak -e 's|/command:/usr/local/bin:/usr/local/sbin:||' \
	-e 's|/command/svc|/usr/bin/svc|' svscanboot 
/bin/cp * /usr/bin 
cd ..
#package/upgrade
package/run
