
// Autogenerated buildcode file - this will change on every make
#define BUILD_CODE "1261840881"
#define BUILD_DATE "Sat Dec 26 20:51:21 IST 2009"
#define BUILD_BOX "Linux loft2500.serverloft.com 2.6.24-26-generic #1 SMP Tue Dec 1 18:37:31 UTC 2009 i686 GNU/Linux"

