/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* "" */
#define AUTORESPOND_PATH "/usr/bin"

/* "" */
#define CATCHALL_ENABLED 1

/* "" */
#define CGIPATH "/cgi-bin/qmailadmin"

/* Define to 1 if the `closedir' function returns void instead of `int'. */
/* #undef CLOSEDIR_VOID */

/* "" */
/* #undef DOMAIN_AUTOFILL */

/* "" */
#define ENABLE_MYSQL 1

/* "" */
#define EZMLMDIR "/usr/local/bin/ezmlm/"

/* "" */
#define EZMLMIDX 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the `dup2' function. */
#define HAVE_DUP2 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `crypt' library (-lcrypt). */
#define HAVE_LIBCRYPT 1

/* Define to 1 if you have the `shadow' library (-lshadow). */
/* #undef HAVE_LIBSHADOW */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the `mkdir' function. */
#define HAVE_MKDIR 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* "" */
/* #undef HELP */

/* "" */
#define HTMLLIBDIR "/usr/local/share/qmailadmin"

/* "" */
#define IMAGEURL "/qmailadmin/images"

/* "" */
/* #undef IPAUTH */

/* "" */
#define MAXALIASESPERPAGE 25

/* "" */
#define MAXUSERSPERPAGE 15

/* "" */
#define MODIFY_QUOTA 1

/* "" */
/* #undef MODIFY_SPAM */

/* "" */
/* #undef MODIFY_SPAM_NEED_EMAIL */

/* "" */
/* #undef NO_CACHE */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* "" */
#define QA_PACKAGE "qmailadmin"

/* "" */
#define QA_VERSION "1.2.13"

/* "" */
#define QMAILDIR "/var/qmail"

/* "" */
#define SPAM_COMMAND "|preline /usr/local/bin/maildrop /etc/mailfilter"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* "" */
#define TRIVIAL_PASSWORD_ENABLED 1

/* "" */
#define USER_INDEX 1

/* "" */
#define VPOPGROUP "vchkpw"

/* "" */
#define VPOPUSER "vpopmail"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
