#!/bin/bash

# description: the qmail MTA

PATH=/var/qmail/bin:/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH

QMAILDUID=`id -u qmaild`
NOFILESGID=`id -g qmaild`

case "$1" in
start)
  echo "Starting qmail..."
  echo ""
  for i in qmail-send qmail-smtpd qmail-smtpds qmail-pop3d; do     
     if svok /service/$i ;  then
        svc -u /service/$i /service/$i/log
        echo "Starting $i"
     else
	echo "$i supervise not running"
     fi
  done

  if [ -d /var/lock/subsys ]; then
     touch /var/lock/subsys/qmail
  fi
  ;;
stop)
   echo "Stopping qmail..."
   echo ""
   for i in qmail-send qmail-smtpd qmail-smtpds qmail-pop3d; do     
	echo " $i"
	svc -d /service/$i /service/$i/log
   done
   if [ -f /var/lock/subsys/qmail ] ; then
       rm /var/lock/subsys/qmail
   fi
   ;;
stat)
   for i in qmail-send qmail-smtpd qmail-smtpds qmail-pop3d; do
	svstat /service/$i
	svstat /service/$i/log
   done
   qmail-qstat
   ;;
doqueue|alrm|flush)
   echo "Flushing timeout table and sending ALRM signal to qmail-send."
   /var/qmail/bin/qmail-tcpok
   svc -a /service/qmail-send
   ;;
queue)
   qmail-qstat
   qmail-qread
   ;;
reload|hup)
   echo "Sending HUP signal to qmail-send."
   svc -h /service/qmail-send
   ;;
pause)
   echo "Pausing qmail-send"
   for i in qmail-send qmail-smtpd qmail-smtpds qmail-pop3d; do
	svc -p /service/$i
	echo "Pausing $i"
   done
   ;;
cont)
   for i in qmail-send qmail-smtpd qmail-smtpds qmail-pop3d; do
	echo "Continuing $i"
	svc -c /service/$i
   done
   ;;
restart)
   echo "Restarting qmail:"
   echo "* Stopping qmail-smtpd."

   svc -d /service/qmail-smtpd /service/qmail-smtpd/log
   svc -d /service/qmail-smtpds /service/qmail-smtpds/log
   echo "* Sending qmail-send SIGTERM and restarting."
   svc -t /service/qmail-send /service/qmail-send/log
   echo "* Sending qmail-pop3d SIGTERM and restarting."
   svc -t /service/qmail-pop3d /service/qmail-pop3d/log
   echo "* Restarting qmail-smtpd."
   svc -u /service/qmail-smtpd /service/qmail-smtpd/log
   svc -u /service/qmail-smtpds /service/qmail-smtpds/log
   ;;
cdb)
   tcprules /etc/tcp.smtp.cdb /etc/tcp.smtp.tmp < /etc/tcp.smtp
   chmod 644 /etc/tcp.smtp.cdb
   echo "Reloaded /etc/tcp.smtp."
   ;;
help)
   cat <<HELP
   stop -- stops mail service (smtp connections refused, nothing goes out)
   start -- starts mail service (smtp connection accepted, mail can go out)
   pause -- temporarily stops mail service (connections accepted, nothing leaves)
   cont -- continues paused mail service
   stat -- displays status of mail service
   cdb -- rebuild the tcpserver cdb file for smtp
   restart -- stops and restarts smtp, sends qmail-send a TERM & restarts it
   doqueue -- schedules queued messages for immediate delivery
   reload -- sends qmail-send HUP, rereading locals and virtualdomains
   queue -- shows status of queue
   alrm -- same as doqueue
   flush -- same as doqueue
   hup -- same as reload
HELP
  ;;
*)
  echo "Usage: $0 {start|stop|restart|doqueue|flush|reload|stat|pause|cont|cdb|queue|help}"
  exit 1
  ;;
esac

exit 0

